AntheaFlores/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Catalog.urls')),
    path('Perfil/', include('AccountManagement.urls')),
    path('adminPanel/',include( 'ProductManagement.urls')),
    path('adminPanel/',include( 'SalesManagement.urls')),
    path('Administracion/Cuentas/',include( 'AccountManagementDjango.urls'))

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Catalog/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from .views import *

app_name="Catalog"

urlpatterns = [
    path('', views.index, name="index"),
    path('Ajax/Search', views.getCards, name="getCards"),
    path('add_product_to_cart/<int:product_id>' , views.add_product_to_cart, name='add_product_to_cart'),
    path('Carrito' , views.getCart, name='getCart'),
    path('Carrito/Eliminar/<int:orderProduct_id>' , views.orderProductDelete, name='orderProductDelete'),
    path('Resumen' , views.orderResume, name='orderResume'),
]

ProductManagement/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name="ProductManagement"

urlpatterns = [

    path('', views.index, name="index"),
    path('EditarProducto/<int:id>', views.productModify, name="productModify"),
    path('productDelete/<int:id>', views.productDelete, name="productDelete"),
    path('CrearProducto', views.productCreate, name="productCreate"),
    path('ListaProductos', views.productList, name="productList")
]

SalesManagement/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name="SalesManagement"

urlpatterns = [
    path('clientBlock/<int:id>', views.clientBlock, name="clientBlock"),
    path('ListaClientes', views.clientList, name="clientList"),
    path('ListaPedidos', views.orderList, name="orderList"),
    path('HistorialPedidos', views.orderHistory, name="orderHistory"),
    path('CambioDeEstado', views.orderStatusChange, name="orderStatusChange"),
]

SalesManagement/forms.py
from django import forms


class ClientSearchForm(forms.Form):
    search = forms.CharField(
        label="Nombre(s)", max_length=200, required=False
    )
    
class OrderSearchForm(forms.Form):
    search = forms.CharField(
        label="Nombre(s)", max_length=200, required=False
    )

class OrderStatusChangeForm(forms.Form):
    order_id = forms.IntegerField(
        label="ID del pedido", required=True
    )
    status = forms.ChoiceField(
        label="Estado del pedido", choices=(
            ("Carrito", "Carrito"), 
            ("Confirmado", "Confirmado"),
            ("Enviado", "Enviado"),
            ("Entregado", "Entregado"),
        )
    )

SalesManagement/views.py
from django.shortcuts import render, redirect
from db.models import *
from .forms import *
from django.contrib.admin.views.decorators import staff_member_required
from django.db.models import Q



@staff_member_required
def clientList(request):
    if request.method == "POST":
        form = ClientSearchForm(request.POST)
        if form.is_valid():
            if form.cleaned_data['search'] == "":
                clientList = User.objects.filter(is_staff=False)
            else:
                clientList = User.objects.filter(
                    (Q (first_name__icontains=form.cleaned_data['search']) |
                    Q (last_name__icontains=form.cleaned_data['search']) |
                    Q (email__icontains=form.cleaned_data['search']) |
                    Q (phone_number__icontains=form.cleaned_data['search'])) &
                    Q (is_staff=False) & Q (is_active=True)
                )
            return render(request, 'SalesManagement/clientList.html', {
                "clientList": clientList,
                 "form": form
            })
    else:
        form = ClientSearchForm()
        return render(request, 'SalesManagement/clientList.html', {
            "clientList": User.objects.filter(is_staff=False, is_active=True ),
            "form": form
        })

@staff_member_required
def clientBlock(request, id):
    if request.method == "POST":
        client = User.objects.get(id=id)
        client.is_active = False
        client.save()
        return redirect('SalesManagement:clientList')


from django.contrib.admin.views.decorators import staff_member_required

@staff_member_required
def orderList(request):
    if request.method == "POST":
        form = OrderSearchForm(request.POST)
        if form.is_valid():
            search = form.cleaned_data['search']
            if search == "":
                orderList = Order.objects.exclude(status__in=['Entregado', 'Carrito']).order_by('-ordered_date')
            else:
                orderList = Order.objects.filter(
                    Q(status__icontains=search) |
                    Q(address__street__icontains=search) |
                    (Q(total=search) if search.isdigit() else Q())
                ).exclude(status__in=['Entregado', 'Carrito']).order_by('-ordered_date')

            return render(request, 'SalesManagement/orderList.html', {
                "orderList": orderList,
                 "form": form
            })
    else:
        form = OrderSearchForm()
        return render(request, 'SalesManagement/orderList.html', {
            "orderList": Order.objects.exclude(status__in=['Entregado', 'Carrito']).order_by('-ordered_date'),
            "form": form
        })

    
from django.contrib.admin.views.decorators import staff_member_required

@staff_member_required
def orderHistory(request):
    if request.method == "POST":
        form = OrderSearchForm(request.POST)
        form2 = OrderStatusChangeForm(request.POST)
        if form.is_valid():
            search = form.cleaned_data['search']
            if search == "":
                orderList = Order.objects.filter(status='Entregado')
            else:
                orderList = Order.objects.filter(
                    Q(status__icontains=search) |
                    Q(address__street__icontains=search) |
                    (Q(total=search) if search.isdigit() else Q()),
                    status='Entregado'
                )
                
            return render(request, 'SalesManagement/orderHistory.html', {
                "orderList": orderList.order_by('-ordered_date'),
                "form": form,
                "form2": form2
            })
    else:
        form = OrderSearchForm()
        form2 = OrderStatusChangeForm()
        return render(request, 'SalesManagement/orderHistory.html', {
            "orderList": Order.objects.filter(status='Entregado').order_by('-ordered_date'),
            "form": form,
            "form2": form2
        })

@staff_member_required
def orderStatusChange(request):
    if request.method == "POST":
        form = OrderStatusChangeForm(request.POST)
        if form.is_valid():
            order = Order.objects.get(id=form.cleaned_data['order_id'])
            order.status = form.cleaned_data['status']
            order.save()
            return redirect('SalesManagement:orderList')
    

SalesManagement/templates/SalesManagement/clientList.html
{% load crispy_forms_tags %}
{% include 'layout.html' %}
{% block body %}
<div class="container">
    <div class="row mt-5 justify-content-between">
        <div class="col-12 col-sm-6 text-start">
            <h2>Clientes</h2>
        </div>

    </div>
    <!--Client search form  -->
    <form class="row mt-3" action="{% url 'SalesManagement:clientList' %}" method="POST">
        {% csrf_token %}
        <div class="col-12">
            <label class="visually-hidden" for="inlineFormInputGroupUsername">Buscar Clientes</label>
            <div class="input-group">
                <div class="input-group-text bg-white"><span class="material-icons" style="color: #e1c2c1;">
                        search
                    </span></div>
                <input type="text" class="form-control border-start-0" id="id_search" placeholder="Buscar Clientes"
                    name="search" maxlength="200">
            </div>
        </div>
    </form>

    <div class="row">
        <div class="col-12">
            <div class="table-responsive">
                <table class="table ">
                    <thead class="border-bottom font-weight-bold">
                        <tr>
                            <td>Correo</td>
                            <td>Nombre</td>
                            <td>Teléfono</td>
                            <td class="text-center">Acciones</td>
                        </tr>
                    </thead>
                    <tbody>
                        {% for client in clientList %}
                        <!-- Button trigger modal -->


                        <!-- Modal -->
                        <div class="modal fade" id="exampleModal{{ client.id }}" tabindex="-1"
                            aria-labelledby="exampleModalLabel" aria-hidden="true">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h1 class="modal-title fs-5" id="exampleModalLabel">Bloquear {{ client.name }}
                                        </h1>
                                        <button type="button" class="btn-close" data-bs-dismiss="modal"
                                            aria-label="Close"></button>
                                    </div>
                                    <div class="modal-body">
                                        Estas seguro que deseas Bloquear el Cliente?
                                    </div>
                                    <div class="modal-footer">
                                        <form action="{% url 'SalesManagement:clientBlock' client.id %}" method="post">
                                            {% csrf_token %}
                                            <button type="submit" class="btn btn-antheaPink text-white"
                                                style="width: 100px !important; height: 35px !important;"> <i
                                                    class="fa fa-trash"></i> Bloquear</button>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <tr>

                            <td>{{client.email}}</td>
                            <td>{{client.first_name}} {{ client.last_name }}</td>
                            <td>{{client.phoneNumber}}</td>
                            <td class="text-center">
                                <button type="button" class="btn btn-antheaPink text-white" data-bs-toggle="modal"
                                    data-bs-target="#exampleModal{{ client.id }}">
                                    <i class="fa fa-trash"></i> Bloquear
                                </button>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

{% endblock %}

SalesManagement/templates/SalesManagement/clientModify.html
{% load crispy_forms_tags %}
{% include 'layout.html' %}
{% block body %}
<div class="container">
    <div class="row mt-5 justify-content-center text-center">
        <div class="col-12">
            <h2>Editar {{ product.name }}</h2>
        </div>
    </div>
    <div class="row mt-3 justify-content-center">
        <div class="col-8">
            <div class="card shadow">
                <div class="card-body">
                    <div class="row">
                        <div class="col-12">

                            <form action="{% url 'ProductManagement:productModify' product.id %}" method="POST"
                                enctype="multipart/form-data">
                                {% csrf_token %}
                                <div class="row">
                                    <div class="col-6">
                                        {{ productForm.name|as_crispy_field }}
                                    </div>
                                    <div class="col-4">
                                        {{ productForm.price|as_crispy_field }}
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-6">
                                        {{ productForm.description|as_crispy_field }}
                                    </div>
                                    <div class="col-6">
                                        {{ productForm.image|as_crispy_field|safe }}
                                        <img id="image-preview" src="#" alt="Preview"
                                            style="max-width: 200px; max-height: 200px; display: none;" />

                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-6">
                                        {{ productForm.available|as_crispy_field }}
                                    </div>
                                </div>
                                <div class="row justify-content-end">
                                    <div class="col-6 text-end">
                                        <button class="btn btn-primary text-white" type="submit"
                                            style="background-color: #e1c2c1; border-color: #e1c2c1;">Guardar
                                            cambios</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    function previewImage(event) {
        var reader = new FileReader();
        var imagePreview = document.getElementById("image-preview");

        reader.onload = function () {
            if (reader.readyState == 2) {
                imagePreview.style.display = "block";
                imagePreview.src = reader.result;
            }
        }

        reader.readAsDataURL(event.target.files[0]);
    }
</script>
{% endblock %}

SalesManagement/templates/SalesManagement/orderHistory.html
{% load crispy_forms_tags %}
{% include 'layout.html' %}
{% block body %}
<div class="container">
    <div class="row mt-5 justify-content-between">
        <div class="col-12 col-sm-6 text-start">

            <h2>Pedidos</h2>
        </div>
    </div>
    <!--Client search form  -->
    <form class="row mt-3" action="{% url 'SalesManagement:orderHistory' %}" method="POST">
        {% csrf_token %}
        <div class="col-12">
            <label class="visually-hidden" for="inlineFormInputGroupUsername">Buscar Pedidos</label>
            <div class="input-group">
                <div class="input-group-text bg-white"><span class="material-icons" style="color: #e1c2c1;">
                        search
                    </span></div>
                <input type="text" class="form-control border-start-0" id="id_search" placeholder="Buscar Pedidos"
                    name="search" maxlength="200">
            </div>
        </div>
    </form>

    <div class="row">
        <div class="col-12">
            <div class="table-responsive">
                <table class="table ">
                    <thead class="border-bottom font-weight-bold">
                        <tr>

                            <td>Id</td>
                            <td>Fecha de pedido</td>
                            <td>Ultima modificación</td>
                            <td>Dirección</td>
                            <td>Total</td>
                            <td>Estado</td>
                        </tr>
                    </thead>
                    <tbody>
                        {% for order in orderList %}
                        <!-- Button trigger modal -->
                        <tr class="align-middle user-select-none">
                            <td>{{order.id}}</td>
                            <td>{{order.ordered_date}}</td>
                            <td>{{order.start_date}}</td>
                            <td>{{order.address}}</td>
                            <td>${{order.total}}</td>
                            {% if order.status == 'Carrito' %}
                            <td>
                                <div class="btn btn-antheaPink text-white disabled">
                                    <span class="material-icons align-middle ">
                                        shopping_cart
                                    </span>
                                    {{order.status}}
                                </div>

                            </td>
                            {% elif order.status == 'Confirmado' %}
                            <td>
                                <div class="btn btn-antheaPink text-white disabled">
                                    <span class="material-icons align-middle ">
                                        shopping_cart
                                    </span>
                                    {{order.status}}
                                </div>
                            </td>
                            {% elif order.status == 'Enviado' %}
                            <td>
                                <div class="btn btn-antheaPink text-white disabled">
                                    <span class="material-icons align-middle ">
                                        shopping_cart
                                    </span>
                                    {{order.status}}
                                </div>
                            </td>
                            {% elif order.status == 'Entregado' %}
                            <td>
                                <div class="btn btn-antheaPink text-white disabled">
                                    <span class="material-icons align-middle ">
                                        shopping_cart
                                    </span>
                                    {{order.status}}
                                </div>
                            </td>
                            {% endif %}
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

{% endblock %}

SalesManagement/templates/SalesManagement/orderList.html
{% load crispy_forms_tags %}
{% include 'layout.html' %}
{% block body %}
<div class="container">
    <div class="row mt-5 justify-content-between">
        <div class="col-12 col-sm-6 text-start">

            <h2>Pedidos</h2>
        </div>
    </div>
    <!--Client search form  -->
    <form class="row mt-3" action="{% url 'SalesManagement:orderList' %}" method="POST">
        {% csrf_token %}
        <div class="col-12">
            <label class="visually-hidden" for="inlineFormInputGroupUsername">Buscar Pedidos</label>
            <div class="input-group">
                <div class="input-group-text bg-white"><span class="material-icons" style="color: #e1c2c1;">
                        search
                    </span></div>
                <input type="text" class="form-control border-start-0" id="id_search" placeholder="Buscar Pedidos"
                    name="search" maxlength="200">
            </div>
        </div>
    </form>

    <div class="row">
        <div class="col-12">
            <div class="table-responsive">
                <table class="table ">
                    <thead class="border-bottom font-weight-bold">
                        <tr>
                            <td>Id</td>
                            <td>Fecha de pedido</td>
                            <td>Ultima modificación</td>
                            <td>Dirección</td>
                            <td>Total</td>
                            <td>Estado</td>
                            <td class="text-center">Cambio de estado</td>
                        </tr>
                    </thead>
                    <tbody>
                        {% for order in orderList %}

                        <!-- Modal -->
                        <div class="modal fade" id="exampleModal{{ order.id }}" tabindex="-1"
                            aria-labelledby="exampleModalLabel" aria-hidden="true">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h1 class="modal-title fs-5" id="exampleModalLabel">Modificar pedido
                                            {{order.id}}
                                        </h1>
                                        <button type="button" class="btn-close" data-bs-dismiss="modal"
                                            aria-label="Close"></button>
                                    </div>
                                    <form action="{% url 'SalesManagement:orderStatusChange' %}" method="POST">
                                        <div class="modal-body">
                                            {% csrf_token %}
                                            Selecciona un estado para el pedido
                                            <input type="hidden" name="order_id" value="{{ order.id }}">
                                            Selecciona un estado para el pedido
                                            <select name="status" class="form-control">
                                                <option value="Carrito" {% if order.status == 'Carrito' %}selected{% endif %}>Carrito</option>
                                                <option value="Confirmado" {% if order.status == 'Confirmado' %}selected{% endif %}>Confirmado</option>
                                                <option value="Enviado" {% if order.status == 'Enviado' %}selected{% endif %}>Enviado</option>
                                                <option value="Entregado" {% if order.status == 'Entregado' %}selected{% endif %}>Entregado</option>
                                            </select>

                                            <input type="hidden" name="id" value="{{ order.id }}">
                                        </div>
                                        <div class="modal-footer">
                                            <button type="submit" class="btn btn-antheaPink text-white">                                                
                                                Cambiar estado
                                            </button>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                        <!-- Button trigger modal -->
                        <tr class="align-middle user-select-none">
                            <td>{{order.id}}</td>
                            <td>{{order.ordered_date}}</td>
                            <td>{{order.start_date}}</td>
                            <td>{{order.address}}</td>
                            <td>${{order.total}}</td>
                            {% if order.status == 'Carrito' %}
                            <td>
                                <div class="btn btn-antheaPink text-white disabled">
                                    <span class="material-icons align-middle ">
                                        shopping_cart
                                    </span>
                                    {{order.status}}
                                </div>
                            </td>
                            {% elif order.status == 'Confirmado' %}
                            <td>
                                <div class="btn btn-antheaPink text-white disabled">
                                    <span class="material-icons align-middle ">
                                        done
                                    </span>
                                    {{order.status}}
                                </div>
                            </td>
                            {% elif order.status == 'Enviado' %}
                            <td>
                                <div class="btn btn-antheaPink text-white disabled">
                                    <span class="material-icons align-middle ">
                                        local_shipping
                                    </span>
                                    {{order.status}}
                                </div>
                            </td>
                            {% elif order.status == 'Entregado' %}
                            <td>
                                <div class="btn btn-antheaPink text-white disabled">
                                    <span class="material-icons align-middle ">
                                        check_circle
                                    </span>
                                    {{order.status}}
                                </div>
                            </td>
                            {% endif %}
                            <td class="text-end">
                                <button type="button" class="btn btn-antheaPink text-white" data-bs-toggle="modal"
                                    data-bs-target="#exampleModal{{ order.id }}">
                                    <i class="fa fa-pencil"></i> Editar estado

                                </button>
                            </td>
                        </tr>
                        {% endfor %}


                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

{% endblock %}