AccountManagement/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name="AccountManagement"

urlpatterns = [
    # Perfil
    path('' , views.userProfile, name="userProfile"),
    path('MiCuenta' , views.myAccount, name="myAccount"),
    
    # Compras
    path('MisPedidos' , views.orderList, name="orderList"),
    # Direcciones
    path('Direcciones' , views.addressList, name="addressList"),
    path('CrearDirección' , views.addressCreate, name="addressCreate"),
    path('ModificarDirección/<int:id>' , views.addressModify, name="addressModify"),
    path('EliminarDirección/<int:id>' , views.addressDelete, name="addressDelete"),
    path('add_product_to_cart/<int:product_id>' , views.add_product_to_cart, name="add_product_to_cart"),
]

AntheaFlores/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Catalog.urls')),
    path('Perfil/', include('AccountManagement.urls')),
    path('adminPanel/',include( 'ProductManagement.urls')),
    path('adminPanel/',include( 'SalesManagement.urls')),
    path('Administracion/Cuentas/',include( 'AccountManagementDjango.urls'))

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Catalog/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from .views import *

app_name="Catalog"

urlpatterns = [
    path('', views.index, name="index"),
    path('Ajax/Search', views.getCards, name="getCards"),
    path('add_product_to_cart/<int:product_id>' , views.add_product_to_cart, name='add_product_to_cart'),
    path('Carrito' , views.getCart, name='getCart'),
    path('Carrito/Eliminar/<int:orderProduct_id>' , views.orderProductDelete, name='orderProductDelete'),
    path('Resumen' , views.orderResume, name='orderResume'),
]

AccountManagement/forms.py
from django import forms
from db import models

class DeliveryAddressForm(forms.ModelForm):
    class Meta:
        model = models.DeliveryAddress
        fields = [ 'street', 'outdoorNumber', 'internalNumber', 'district', 'municipally', 'state', 'reference', 'postalCode']


class OrderSearchForm(forms.Form):
    search = forms.CharField(label='Search', max_length=100, required=False)

class DeliveryAddressSearchForm(forms.Form):
    search = forms.CharField(label='Search', max_length=100, required=False)
    

AccountManagement/views.py
from django.shortcuts import redirect, render
from db.models import *
from .forms import *
from django.db.models import Q
from django.contrib.auth.decorators import login_required

# Create your views here.
@login_required
def userProfile(request):
    return render(request, 'AccountManagement/userProfile.html')
@login_required
def myAccount(request):
    client = request.user
    return render(request, 'AccountManagement/myAccount.html',{
        'client': client
    })
@login_required
def orderList(request):
    if request.method =="POST":
        form = OrderSearchForm(request.POST)
        if form.is_valid():
            if form.cleaned_data['search'] == "":
                orderList = Order.objects.all()
            else:
                orderList = Order.objects.filter(
                    Q(status__icontains=form.cleaned_data['search']) |
                    Q(address__street__icontains=form.cleaned_data['search']) |
                    Q(total__icontains=form.cleaned_data['search']) 
                
                )
            return render(request, 'AccountManagement/orderList.html', {
                "orderList": orderList,
                 "form": form
            })

    else:  
        if Order.objects.filter(client=request.user, status="Carrito").exists():
            orderList = Order.objects.filter(client=request.user, status="Carrito")
        orderList = Order.objects.filter(client=request.user)
        return render(request, 'AccountManagement/orderList.html',{
            'orderList': orderList
        })
    
@login_required    
def addressList(request):
    if request.method =="POST":
        form = DeliveryAddressSearchForm(request.POST)
        if form.is_valid():
            search = form.cleaned_data['search']
            query = (
                Q(street__icontains=search) |
                Q(district__icontains=search) |
                Q(municipally__name__icontains=search) |
                Q(state__name__icontains=search) |
                Q(reference__icontains=search)
            )
            if search.isdigit():
                query = query | Q(internalNumber=search) | Q(outdoorNumber=search) | Q(postalCode=search)
            
            if search == "":
                addressList = DeliveryAddress.objects.filter(disable=False, client=request.user)
            else:
                addressList = DeliveryAddress.objects.filter(query & Q(client=request.user) & Q(disable=False))

            return render(request, 'AccountManagement/deliveryAddressList.html', {
                "addressList": addressList,
                 "form": form
            })
    else:
        addressList = DeliveryAddress.objects.filter(client=request.user, disable=False)
        return render(request, 'AccountManagement/deliveryAddressList.html',{
            'addressList': addressList
        })


@login_required
def addressCreate(request):
    if request.method == "POST":
        form = DeliveryAddressForm(request.POST)
        if form.is_valid():
            delivery_address = form.save(commit=False)
            delivery_address.client = request.user
            delivery_address.save()
            return redirect('AccountManagement:addressList')
        else:
            return render(request, 'AccountManagement/addressCreate.html', {'form': form})
    else:
        form = DeliveryAddressForm()
        return render(request, 'AccountManagement/addressCreate.html', {'form': form})

@login_required
def addressModify(request, id):
    address = DeliveryAddress.objects.get(id=id)
    if request.method == "POST":
        form = DeliveryAddressForm(request.POST, instance=address)
        if form.is_valid():
            form.save()
            return redirect('AccountManagement:addressList')
        else:
            return render(request, 'AccountManagement/addressModify.html', {'form': form, 'address': address})
    else:
        form = DeliveryAddressForm(instance=address)
        return render(request, 'AccountManagement/addressModify.html', {'form': form, 'address': address})

@login_required
def addressDelete(request, id):
    address = DeliveryAddress.objects.get(id=id)
    if request.method == "POST":
        address.disable=True
        address.save()
        return redirect('AccountManagement:addressList')
    
@login_required
def add_product_to_cart(request, product_id):
    if request.method == "POST":
        quantity = request.POST['quantity']
        product = Product.objects.get(id=product_id)
        if Order.objects.filter(client=request.user, status="Carrito").exists():
            order = Order.objects.get(client=request.user, status="Carrito")
        else:
            order = Order.objects.create(client=request.user, status="Carrito")
        orderProduct = OrderProduct.objects.create(order=order, product=product, quantity=quantity, price=product.price)
        order.total += orderProduct.price
        order.save()
        return redirect('AccountManagement:orderList')

MyAccount/views.py
from django.shortcuts import render
from db import models

def product_list(request):
    context = {
        'products': models.Product.all()
    }

    return render(request, "products_list.html", context)

AccountManagement/templates/AccountManagement/addressCreate.html
{% load crispy_forms_tags %}
{% include 'layout.html' %}
{% block body %}
<div class="container">
    <div class="row mt-5 justify-content-center text-center">
        <div class="col-12">
            <h2>Registro de direcciones</h2>
        </div>
    </div>
    <div class="row mt-3 justify-content-center">
        <div class="col-8">
            <div class="card shadow">
                <div class="card-body">
                    <div class="row">
                        <div class="col-12">
                            <form action="{% url 'AccountManagement:addressCreate' %}" method="POST"
                                enctype="multipart/form-data">
                                {% csrf_token %}
                                <div class="row">
                                    <div class="col-4">
                                        {{ form.internalNumber|as_crispy_field }}
                                    </div>
                                    <div class="col-4">
                                        {{ form.outdoorNumber|as_crispy_field }}
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-12">
                                        {{ form.street|as_crispy_field }}
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-6">
                                        {{ form.postalCode|as_crispy_field }}
                                    </div>
                                    <div class="col-6">
                                        {{ form.district|as_crispy_field }}
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-6">
                                        {{ form.municipally|as_crispy_field }}
                                    </div>
                                    <div class="col-6">
                                        {{ form.state|as_crispy_field }}
                                    </div>
                                </div>
                                <div class="row mb-3">
                                    <div class="col-12">
                                        {{ form.reference|as_crispy_field }}

                                    </div>
                                </div>
                                <div class="row justify-content-end">
                                    <div class="col-6 text-end">
                                        <button class="btn btn-primary text-white" type="submit"
                                            style="background-color: #e1c2c1; border-color: #e1c2c1;">Registrar nueva
                                            dirección</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

AccountManagement/templates/AccountManagement/addressModify.html
{% load crispy_forms_tags %}
{% include 'layout.html' %}
{% block body %}
<div class="container">
    <div class="row mt-5 justify-content-center text-center">
        <div class="col-12">
            <h2>Modificar dirección</h2>
        </div>
    </div>
    <div class="row mt-3 justify-content-center">
        <div class="col-8">
            <div class="card shadow">
                <div class="card-body">
                    <div class="row">
                        <div class="col-12">
                            <form action="{% url 'AccountManagement:addressModify' address.id %}" method="POST"
                                enctype="multipart/form-data">
                                {% csrf_token %}
                                <div class="row">
                                    <div class="col-4">
                                        {{ form.internalNumber|as_crispy_field }}
                                    </div>
                                    <div class="col-4">
                                        {{ form.outdoorNumber|as_crispy_field }}
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-12">
                                        {{ form.street|as_crispy_field }}
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-6">
                                        {{ form.postalCode|as_crispy_field }}
                                    </div>
                                    <div class="col-6">
                                        {{ form.district|as_crispy_field }}
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-6">
                                        {{ form.municipally|as_crispy_field }}
                                    </div>
                                    <div class="col-6">
                                        {{ form.state|as_crispy_field }}
                                    </div>
                                </div>
                                <div class="row mb-3">
                                    <div class="col-12">
                                        {{ form.reference|as_crispy_field }}

                                    </div>
                                </div>
                                <div class="row justify-content-end">
                                    <div class="col-6 text-end">
                                        <button class="btn btn-primary text-white" type="submit"
                                            style="background-color: #e1c2c1; border-color: #e1c2c1;">Registrar
                                            cambios</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

AccountManagement/templates/AccountManagement/deliveryAddressList.html
{% load crispy_forms_tags %}
{% include 'layout.html' %}
{% block body %}
<div class="container">

    <div class="row mt-5 justify-content-between">
        <div class="col-12 col-sm-6 text-start">
            <a class="btn btn-antheaPink text-white mb-2" href="{% url 'AccountManagement:userProfile' %}">
                <h5 class="card-title">
                    <span class="material-icons align-middle" style="color: #FFFF;">
                        arrow_back_ios
                    </span>
                    Regresar
                </h5>
            </a>
            <h2>Direcciones</h2>
        </div>
        <div class="col-12 col-sm-6 text-end">
            <a class="btn btn-antheaPink text-white" href="{% url 'AccountManagement:addressCreate' %}">
                Registrar nueva
                dirección</a>
        </div>
    </div>
    <form class="row mt-3" action="{% url 'AccountManagement:addressList' %}" method="POST">
        {% csrf_token %}
        <div class="col-12">
            <label class="visually-hidden" for="inlineFormInputGroupUsername">Buscar Direcciones</label>
            <div class="input-group">
                <div class="input-group-text bg-white"><span class="material-icons" style="color: #e1c2c1;">
                        search
                    </span></div>
                <input type="text" class="form-control border-start-0" id="id_search" placeholder="Buscar Direcciones"
                    name="search" maxlength="200">
            </div>
        </div>
    </form>
    <div class="row">
        <div class="col-12">
            <div class="table-responsive">
                <table class="table ">
                    <thead class="border-bottom font-weight-bold">
                        <tr>
                            <td>Dirección</td>
                            <td class="text-center">Acciones</td>
                        </tr>
                    </thead>
                    <tbody>
                        {% for deliveryAddress in addressList %}
                        <!-- Button trigger modal -->


                        <!-- Modal -->
                        <div class="modal fade" id="exampleModal{{ deliveryAddress.id }}" tabindex="-1"
                            aria-labelledby="exampleModalLabel" aria-hidden="true">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h1 class="modal-title fs-5" id="exampleModalLabel">Eliminar
                                            {{ deliveryAddress }}
                                        </h1>
                                        <button type="button" class="btn-close" data-bs-dismiss="modal"
                                            aria-label="Close"></button>
                                    </div>
                                    <div class="modal-body">
                                        Estas seguro que deseas eliminar la dirección?
                                    </div>
                                    <div class="modal-footer">
                                        <form action="{% url 'AccountManagement:addressDelete' deliveryAddress.id %}"
                                            method="post">
                                            {% csrf_token %}
                                            <button type="submit" class="btn btn-antheaPink text-white"
                                                style="width: 100px !important; height: 35px !important;"> <i
                                                    class="fa fa-trash"></i> Eliminar</button>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <tr class="align-middle">

                            <td>{{deliveryAddress}}</td>
                            <td class="text-center">

                                <a href="{% url 'AccountManagement:addressModify' deliveryAddress.id %}"
                                    class="btn btn-antheaPink text-white">
                                    <i class="fa fa-pencil"></i>
                                    Editar
                                </a>

                                <button type="button" class="btn btn-antheaPink text-white" data-bs-toggle="modal"
                                    data-bs-target="#exampleModal{{ deliveryAddress.id }}">
                                    <i class="fa fa-trash"></i> Eliminar

                                </button>

                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

{% endblock %}

AccountManagement/templates/AccountManagement/myAccount.html
{% load crispy_forms_tags %}
{% include 'layout.html' %}
{% load static %}
{% block body %}
<div class="container">
    <div class="row mt-5 justify-content-between mb-3">
        <!-- Botón de regresar -->
        <div class="col-12 col-sm-4 text-start">
            <a class="btn btn-antheaPink text-white" href="{% url 'AccountManagement:userProfile' %}">
                <h5 class="card-title">
                    <span class="material-icons align-middle" style="color: #FFFF;">
                        arrow_back_ios
                    </span>
                    Regresar
                </h5>
            </a>
        </div>
    </div>
    <div class="row gy-3 justify-content-center">
        <div class="col-12 col-md-6">
            <div class="card">
                <div class="row justify-content-center">
                    <div class="col-12 col-md-6">
                        <img src="{% static 'img/antheaLogo-bg.png' %}" class="card-img-top" alt="...">
                    </div>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-12">
                            <h5 class="card-title">Nombre(s)</h5>
                            <p class="card-text">{{ client.first_name }}</p>
                        </div>
                        <hr>
                        <div class="col-12">
                            <h5 class="card-title">Apellido(s)</h5>
                            <p class="card-text">{{ client.last_name }}</p>
                        </div>
                        <hr>
                        <div class="col-12">
                            <h5 class="card-title">Correo</h5>
                            <p class="card-text">{{ client.email }}</p>
                        </div>
                        <hr>
                        <div class="col-12">
                            <h5 class="card-title">Teléfono</h5>
                            <p class="card-text">{{ client.phone_number }}</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

AccountManagement/templates/AccountManagement/orderList.html
{% load crispy_forms_tags %}
{% include 'layout.html' %}
{% block body %}
<div class="container">
    <div class="row mt-5 justify-content-between">
        <div class="col-12 col-sm-6 text-start">
            <a class="btn btn-antheaPink text-white mb-2" href="{% url 'AccountManagement:userProfile' %}">
                <h5 class="card-title">
                    <span class="material-icons align-middle" style="color: #FFFF;">
                        arrow_back_ios
                    </span>
                    Regresar
                </h5>
            </a>
            <h2>Pedidos</h2>
        </div>

    </div>
    <!--Client search form  -->
    <form class="row mt-3" action="{% url 'AccountManagement:orderList' %}" method="POST">
        {% csrf_token %}
        <div class="col-12">
            <label class="visually-hidden" for="inlineFormInputGroupUsername">Buscar Pedidos</label>
            <div class="input-group">
                <div class="input-group-text bg-white"><span class="material-icons" style="color: #e1c2c1;">
                        search
                    </span></div>
                <input type="text" class="form-control border-start-0" id="id_search" placeholder="Buscar Pedidos"
                    name="search" maxlength="200">
            </div>
        </div>
    </form>

    <div class="row">
        <div class="col-12">
            <div class="table-responsive">
                <table class="table ">
                    <thead class="border-bottom font-weight-bold">
                        <tr>
                            <td>Fecha de pedido</td>
                            <td>Ultima modificación</td>
                            <td>Dirección</td>
                            <td>Total</td>
                            <td>Estado</td>
                        </tr>
                    </thead>
                    <tbody>
                        {% for order in orderList %}
                        <!-- Button trigger modal -->
                        <tr class="align-middle user-select-none">
                            <td>{{order.ordered_date}}</td>
                            <td>{{order.start_date}}</td>
                            <td>{{order.address}}</td>
                            <td>${{order.total}}</td>
                            {% if order.status == 'Cart' %}
                            <td>
                                <div class="btn btn-antheaPink text-white disabled">
                                    <span class="material-icons align-middle ">
                                        shopping_cart
                                    </span>
                                    {{order.status}}
                                </div>

                            </td>
                            {% elif order.status == 'Confirmado' %}
                            <td>
                                <div class="btn btn-antheaPink text-white disabled">
                                    <span class="material-icons align-middle ">
                                        shopping_cart
                                    </span>
                                    {{order.status}}
                                </div>
                            </td>
                            {% elif order.status == 'Enviado' %}
                            <td>
                                <div class="btn btn-antheaPink text-white disabled">
                                    <span class="material-icons align-middle ">
                                        shopping_cart
                                    </span>
                                    {{order.status}}
                                </div>
                            </td>
                            {% elif order.status == 'Entregado' %}
                            <td>
                                <div class="btn btn-antheaPink text-white disabled">
                                    <span class="material-icons align-middle ">
                                        shopping_cart
                                    </span>
                                    {{order.status}}
                                </div>
                            </td>
                            {% endif %}
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

{% endblock %}

AccountManagement/templates/AccountManagement/userProfile.html
{% load crispy_forms_tags %}
{% include 'layout.html' %}
{% load static %}
{% block body %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-12 col-sm-4">
            <img src="{% static 'img/antheaLogo-bg.png' %}" class="card-img-top" alt="...">
        </div>
    </div>
    <div class="row mt-3 justify-content-center text-center">
        <div class="col-12">
            <h2>Mi Perfil</h2>
        </div>
    </div>
    <div class="row gy-3">
        <div class="col-12 col-sm-6 col-md-4">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Mis direcciones</h5>
                    <p class="card-text">Agrega, modifica, elimina direcciones.</p>
                    <a href="{% url 'AccountManagement:addressList' %}" class="btn btn-antheaPink text-white">Entrar</a>
                </div>
            </div>
        </div>
        <div class="col-12 col-sm-6 col-md-4">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Mis pedidos</h5>
                    <p class="card-text">Tu listado de pedidos y sus estados.</p>
                    <a href="{% url 'AccountManagement:orderList' %}" class="btn btn-antheaPink text-white">Entrar</a>
                </div>
            </div>
        </div>
        <div class="col-12 col-sm-6 col-md-4">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Mi cuenta</h5>
                    <p class="card-text">Tu información personal.</p>
                    <a href="{% url 'AccountManagement:myAccount' %}" class="btn btn-antheaPink text-white">Entrar</a>
                </div>
            </div>
        </div>

    </div>
</div>

{% endblock %}