AntheaFlores/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Catalog.urls')),
    path('Perfil/', include('AccountManagement.urls')),
    path('adminPanel/',include( 'ProductManagement.urls')),
    path('adminPanel/',include( 'SalesManagement.urls')),
    path('Administracion/Cuentas/',include( 'AccountManagementDjango.urls'))

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Catalog/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from .views import *

app_name="Catalog"

urlpatterns = [
    path('', views.index, name="index"),
    path('Ajax/Search', views.getCards, name="getCards"),
    path('add_product_to_cart/<int:product_id>' , views.add_product_to_cart, name='add_product_to_cart'),
    path('Carrito' , views.getCart, name='getCart'),
    path('Carrito/Eliminar/<int:orderProduct_id>' , views.orderProductDelete, name='orderProductDelete'),
    path('Resumen' , views.orderResume, name='orderResume'),
]

ProductManagement/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name="ProductManagement"

urlpatterns = [

    path('', views.index, name="index"),
    path('EditarProducto/<int:id>', views.productModify, name="productModify"),
    path('productDelete/<int:id>', views.productDelete, name="productDelete"),
    path('CrearProducto', views.productCreate, name="productCreate"),
    path('ListaProductos', views.productList, name="productList")
]

SalesManagement/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name="SalesManagement"

urlpatterns = [
    path('clientBlock/<int:id>', views.clientBlock, name="clientBlock"),
    path('ListaClientes', views.clientList, name="clientList"),
    path('ListaPedidos', views.orderList, name="orderList"),
    path('HistorialPedidos', views.orderHistory, name="orderHistory"),
    path('CambioDeEstado', views.orderStatusChange, name="orderStatusChange"),
]

ProductManagement/forms.py
from django import forms
from db import models

class ProductForm(forms.ModelForm):
    class Meta:
        model = models.Product
        fields = '__all__'

class ProductSearchForm(forms.Form):
    search = forms.CharField(max_length=200, required=False)

ProductManagement/views.py
from django.shortcuts import render, redirect
from db.models import *
from .forms import *
from django.contrib.admin.views.decorators import staff_member_required
from django.db.models import Q

@staff_member_required
def index(request):
    return render(request, 'ProductManagement/index.html')

@staff_member_required
def productCreate(request):
    if request.method == "POST":
        productFormValidation = ProductForm(request.POST, request.FILES)
        if productFormValidation.is_valid():
            productFormValidation.save()
            return redirect('ProductManagement:productList')
        else:
            return render(request, 'ProductManagement/productCreate.html', {
                "productForm": productFormValidation
            })
    else:
        productForm = ProductForm()
        return render(request, 'ProductManagement/productCreate.html', {"productForm": productForm})
    
@staff_member_required
def productList(request):
    if request.method == "POST":
        form = ProductSearchForm(request.POST)
        if form.is_valid():
            if form.cleaned_data['search'] == "":
                productList = Product.objects.all()
            else:
                productList = Product.objects.filter(
                    (Q (name__icontains=form.cleaned_data['search']) |
                    Q (description__icontains=form.cleaned_data['search']) |
                    Q (price__icontains=form.cleaned_data['search'])) 
                )
            return render(request, 'ProductManagement/productList.html', {
                "productList": productList,
                 "form": form
            })
    else:
        return render(request, 'ProductManagement/productList.html', {"productList": Product.objects.all()})

@staff_member_required
def productModify(request, id):
    #Lista de objetos
    allProducts = Product.objects.all()
    # products = Product.objects.filter()

    #Objeto
    product = Product.objects.get(id=id)

    if request.method == "POST":
        productFormValidation = ProductForm(request.POST, request.FILES, instance=product)
        if productFormValidation.is_valid():
            productFormValidation.save()
            return redirect('ProductManagement:productList')
        else:
            return render(request, 'ProductManagement/productModify.html', {
                "product": product,
                "allProducts": allProducts,
                "productForm": productForm,
            })
    else:
        
        productForm = ProductForm(instance=product)
        return render(request, 'ProductManagement/productModify.html', {
            "product": product,
            "allProducts": allProducts,
            "productForm": productForm,
            })

@staff_member_required
def productDelete(request, id):
    if request.method == "POST":
        product = Product.objects.get(id=id)
        product.delete()
        return redirect('ProductManagement:productList')

ProductManagement/templates/ProductManagement/index.html
{% load crispy_forms_tags %}
{% include 'layout.html' %}
{% load static %}
{% block body %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-12 col-sm-4">
            <img src="{% static 'img/antheaLogo-bg.png' %}" class="card-img-top" alt="...">
        </div>
    </div>
    <div class="row mt-3 justify-content-center text-center">
        <div class="col-12">
            <h2>Panel Administrativo</h2>
        </div>
    </div>
    <div class="row gy-3">
        <div class="col-12 col-sm-6 col-md-4">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Productos</h5>
                    <p class="card-text">Listado y administración de productos.</p>
                    <a href="{% url 'ProductManagement:productList' %}" class="btn btn-antheaPink text-white">Entrar</a>
                </div>
            </div>
        </div>
        <div class="col-12 col-sm-6 col-md-4">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Compras</h5>
                    <p class="card-text">Listado y administración de compras.</p>
                    <a href="{% url 'SalesManagement:orderList' %}" class="btn btn-antheaPink text-white">Entrar</a>
                </div>
            </div>
        </div>
        <div class="col-12 col-sm-6 col-md-4">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Historial</h5>
                    <p class="card-text">Listado y administración de historial.</p>
                    <a href="{% url 'SalesManagement:orderHistory' %}" class="btn btn-antheaPink text-white">Entrar</a>
                </div>
            </div>
        </div>
        <div class="col-12 col-sm-6 col-md-4">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Clientes</h5>
                    <p class="card-text">Listado y administración de clientes.</p>
                    <a href="{% url 'SalesManagement:clientList' %}" class="btn btn-antheaPink text-white">Entrar</a>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

ProductManagement/templates/ProductManagement/productCreate.html
{% load crispy_forms_tags %}
{% include 'layout.html' %}
{% block body %}
<div class="container">
    <div class="row mt-5 justify-content-center text-center">
        <div class="col-12">
            <h2>Registro de productos</h2>
        </div>
    </div>
    <div class="row mt-3 justify-content-center">
        <div class="col-8">
            <div class="card shadow">
                <div class="card-body">
                    <div class="row">
                        <div class="col-12">
                            <h1>{{ product.description }}</h1>
                            <form action="{% url 'ProductManagement:productCreate' %}" method="POST"
                                enctype="multipart/form-data">
                                {% csrf_token %}
                                <div class="row">
                                    <div class="col-6">
                                        {{ productForm.name|as_crispy_field }}
                                    </div>
                                    <div class="col-4">
                                        {{ productForm.price|as_crispy_field }}
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-6">
                                        {{ productForm.description|as_crispy_field }}
                                    </div>
                                    <div class="col-6">
                                        {{ productForm.image|as_crispy_field }}
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-6">
                                    </div>
                                </div>
                                <div class="row justify-content-end">
                                    <div class="col-6 text-end">
                                        <button class="btn btn-primary text-white" type="submit"
                                            style="background-color: #e1c2c1; border-color: #e1c2c1;">Registrar nuevo
                                            producto</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

ProductManagement/templates/ProductManagement/productList.html
{% load crispy_forms_tags %}
{% include 'layout.html' %}
{% block body %}
<div class="container">
    <div class="row mt-5 justify-content-between">
        <div class="col-12 col-sm-6 text-start">
            <h2>Productos</h2>
        </div>
        <div class="col-12 col-sm-6 text-end">
            <a class="btn btn-antheaPink text-white" href="{% url 'ProductManagement:productCreate' %}"> Registrar nuevo
                producto</a>
        </div>
    </div>
    <form class="row mt-3" action="{% url 'ProductManagement:productList' %}" method="POST">
        {% csrf_token %}
        <div class="col-12">
            <label class="visually-hidden" for="inlineFormInputGroupUsername">Buscar Productos</label>
            <div class="input-group">
                <div class="input-group-text bg-white"><span class="material-icons" style="color: #e1c2c1;">
                        search
                    </span></div>
                <input type="text" class="form-control border-start-0" id="id_search" placeholder="Buscar Productos"
                    name="search" maxlength="200">
            </div>
        </div>
    </form>
    <div class="row">
        <div class="col-12">
            <div class="table-responsive">
                <table class="table ">
                    <thead class="border-bottom font-weight-bold">
                        <tr>
                            <td>Imagen</td>
                            <td>Nombre</td>
                            <td>Descripción</td>
                            <td>Precio</td>
                            <td class="text-center">Acciones</td>
                        </tr>
                    </thead>
                    <tbody>
                        {% for product in productList %}
                        <!-- Button trigger modal -->


                        <!-- Modal -->
                        <div class="modal fade" id="exampleModal{{ product.id }}" tabindex="-1"
                            aria-labelledby="exampleModalLabel" aria-hidden="true">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h1 class="modal-title fs-5" id="exampleModalLabel">Eliminar {{ product.name }}
                                        </h1>
                                        <button type="button" class="btn-close" data-bs-dismiss="modal"
                                            aria-label="Close"></button>
                                    </div>
                                    <div class="modal-body">
                                        Estas seguro que deseas eliminar el producto?
                                    </div>
                                    <div class="modal-footer">
                                        <form action="{% url 'ProductManagement:productDelete' product.id %}"
                                            method="post">
                                            {% csrf_token %}
                                            <button type="submit" class="btn btn-antheaPink text-white"
                                                style="width: 100px !important; height: 35px !important;"> <i
                                                    class="fa fa-trash"></i> Eliminar</button>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <tr>
                            {% if product.image %}
                            <td>
                                <img src="{{ product.image.url }}"
                                    alt="https://img-9gag-fun.9cache.com/photo/a3Q5VW5_460s.jpg"
                                    style="max-width: 100px;">
                            </td>
                            {% else %}
                            <td>
                            </td>
                            {% endif %}
                            <td>{{product.name}}</td>
                            <td>{{product.description}}</td>
                            <td>${{product.price}}</td>
                            <td class="text-end">

                                <a href="{% url 'ProductManagement:productModify' product.id %}"
                                    class="btn btn-antheaPink text-white mb-2"
                                    style="width: 100px !important; height: 35px !important;"><i
                                        class="fa fa-pencil"></i>
                                    Editar
                                </a>

                                <button type="button" class="btn btn-antheaPink text-white" data-bs-toggle="modal"
                                    data-bs-target="#exampleModal{{ product.id }}">
                                    <i class="fa fa-trash"></i> Eliminar

                                </button>

                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

{% endblock %}

ProductManagement/templates/ProductManagement/productModify.html
{% load crispy_forms_tags %}
{% include 'layout.html' %}
{% block body %}
<div class="container">
    <div class="row mt-5 justify-content-center text-center">
        <div class="col-12">
            <h2>Editar {{ product.name }}</h2>
        </div>
    </div>
    <div class="row mt-3 justify-content-center">
        <div class="col-8">
            <div class="card shadow">
                <div class="card-body">
                    <div class="row">
                        <div class="col-12">

                            <form action="{% url 'ProductManagement:productModify' product.id %}" method="POST"
                                enctype="multipart/form-data">
                                {% csrf_token %}
                                <div class="row">
                                    <div class="col-6">
                                        {{ productForm.name|as_crispy_field }}
                                    </div>
                                    <div class="col-4">
                                        {{ productForm.price|as_crispy_field }}
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-6">
                                        {{ productForm.description|as_crispy_field }}
                                    </div>
                                    <div class="col-6">
                                        {{ productForm.image|as_crispy_field|safe }}
                                        <img id="image-preview" src="#" alt="Preview"
                                            style="max-width: 200px; max-height: 200px; display: none;" />

                                    </div>
                                </div>
                                <div class="row justify-content-end">
                                    <div class="col-6 text-end">
                                        <button class="btn btn-primary text-white" type="submit"
                                            style="background-color: #e1c2c1; border-color: #e1c2c1;">Guardar
                                            cambios</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    function previewImage(event) {
        var reader = new FileReader();
        var imagePreview = document.getElementById("image-preview");

        reader.onload = function () {
            if (reader.readyState == 2) {
                imagePreview.style.display = "block";
                imagePreview.src = reader.result;
            }
        }

        reader.readAsDataURL(event.target.files[0]);
    }
</script>
{% endblock %}