AccountManagement/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name="AccountManagement"

urlpatterns = [
    # Perfil
    path('' , views.userProfile, name="userProfile"),
    path('MiCuenta' , views.myAccount, name="myAccount"),
    
    # Compras
    path('MisPedidos' , views.orderList, name="orderList"),
    # Direcciones
    path('Direcciones' , views.addressList, name="addressList"),
    path('CrearDirección' , views.addressCreate, name="addressCreate"),
    path('ModificarDirección/<int:id>' , views.addressModify, name="addressModify"),
    path('EliminarDirección/<int:id>' , views.addressDelete, name="addressDelete"),
    path('add_product_to_cart/<int:product_id>' , views.add_product_to_cart, name="add_product_to_cart"),
]

AntheaFlores/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Catalog.urls')),
    path('Perfil/', include('AccountManagement.urls')),
    path('adminPanel/',include( 'ProductManagement.urls')),
    path('adminPanel/',include( 'SalesManagement.urls')),
    path('Administracion/Cuentas/',include( 'AccountManagementDjango.urls'))

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Catalog/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from .views import *

app_name="Catalog"

urlpatterns = [
    path('', views.index, name="index"),
    path('Ajax/Search', views.getCards, name="getCards"),
    path('add_product_to_cart/<int:product_id>' , views.add_product_to_cart, name='add_product_to_cart'),
    path('Carrito' , views.getCart, name='getCart'),
    path('Carrito/Eliminar/<int:orderProduct_id>' , views.orderProductDelete, name='orderProductDelete'),
    path('Resumen' , views.orderResume, name='orderResume'),
]

ProductManagement/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name="ProductManagement"

urlpatterns = [

    path('', views.index, name="index"),
    path('EditarProducto/<int:id>', views.productModify, name="productModify"),
    path('productDelete/<int:id>', views.productDelete, name="productDelete"),
    path('CrearProducto', views.productCreate, name="productCreate"),
    path('ListaProductos', views.productList, name="productList")
]

templates/layout.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Anthea Flores</title>
  <link rel=" stylesheet" href="{% static 'masterSCSS/globalMaster.css' %}">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
</head>

<body>
  {% include 'navBar.html' %}
  {% block body %}
    
  {% endblock %}
  <div class="mb-5">

  </div>
  <!-- Popper for Bootstrap-->
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js"
    integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous">
    </script>

  <!-- Bootstrap JS -->
  <script src="{% static 'bootstrap/js/bootstrap.js' %}"></script>
</body>

</html>

templates/navBar.html
{% load static %}

<nav class="navbar navbar-expand-lg bg-light shadow">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'Catalog:index' %}">
      <img src="{% static 'img/antheaLogo-bg.png' %}" alt="Logo" class="d-inline-block align-text-top"
        style="max-height: 100px;">

    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">

      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">

        <li class="nav-item">
          <a class="nav-link active " aria-current="page" href="{% url 'Catalog:getCart' %}">
            <span class="material-icons  position-relative" style="color: #e1c2c1;">
              shopping_cart
              <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-antheaPink text-white h-100 w-100">
                10
              </span>
            </span>
            Carrito
          </a>
        </li>
        {% if request.user.is_authenticated %}
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <span class="material-icons align-bottom" style="color: #e1c2c1;">
              account_circle
            </span>
            {{request.user}}
          </a>
          <ul class="dropdown-menu">
            {% if request.user.is_staff %}
            <li><a class="dropdown-item" href="{% url 'ProductManagement:index' %}">Admin Panel</a></li>
            <li>
              <hr class="dropdown-divider">
            </li>
            <li><a class="dropdown-item" href="{% url 'logout' %}">Cerrar sesión</a></li>
            {% else %}
            <li><a class="dropdown-item" href="{% url 'AccountManagement:userProfile' %}">Perfil</a></li>
            <li><a class="dropdown-item" href="#">Mis pedidos</a></li>
            <li>
              <hr class="dropdown-divider">
            </li>
            <li><a class="dropdown-item" href="{% url 'logout' %}">Cerrar sesión</a></li>
            {% endif %}
          </ul>
        </li>
        {% else %}
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <span class="material-icons align-bottom" style="color: #e1c2c1;">
              account_circle
            </span>
            Inicia sesión
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{% url 'login' %}">Inicia sesión</a></li>
        </li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>